let readline = require("readline-sync")
console.log("--------------------Formulario de cadastro-----------------------------")
let nome = readline.question("Qual o seu Nome Completo: ")
let dia = readline.question("Informe o dia do seu nascimento: ")
let mes = readline.question("Informe o mes do seu Nascimento: ")
let ano = readline.question("Informe o ano do seu Nascimento: ")
let filho = readline.question("Informe se tem filhos: ")
let estado = readline.question("Informe o estado que nasceu: ")
let cidade = readline.question("Informe a cidade que nasceu: ")
let hobby = readline.question("Informe qual o seu hobby: ")
let sonho = readline.question("Informe o seu maior sonho: ")
let animais = readline.question("Informe se tem animais em casa: ")
let desafio = readline.question("Informe seu maior desafio: ")
let concelho = readline.question("Informe um concelho para as pessoas: ")

console.log(`--------------------${nome}-----------------------------`)
console.log (`Data de nascimento: ${dia}/${mes}/${ano}`)
console.log(`filho: ${filho} `)
console.log (`estado: ${estado}`)
console.log (`Cidade: ${cidade}`)
console.log (`Hobby: ${hobby}`)
console.log (`sonho: ${sonho}`)
console.log (`Animais:${animais}`)
console.log (`Desafio:${desafio}`)
console.log (`concelho:${concelho}`)

console.log(`--------------------------------------------------------`)
